### ISSUE TITLE
Dimensions and positions badly calculated for multihead Randr setup

### ISSUE THREAD

**Issue by lobre** [pekwm/pekwm#193]
Hey,

I am testing PekWM for the first time on my work setup, where I have my internal laptop `eDP-1`, alongside two external monitors. `DP-1` is above my laptop and is a bit wider, and `HDMI-1` is to the left, 90 degrees rotated. Here is a screenshot of `arandr` to better visualise what it means.

<img width="760" height="589" alt="Image" src="https://github.com/user-attachments/assets/8cfbf4d1-0dbc-4dbc-b2fb-8bc8191dc333" />

Here is the size and position of each monitor:

```
xrandr --listmonitors
Monitors: 3
 0: +*DP-1 3840/600x2160/340+2160+654  DP-1
 1: +eDP-1 2880/301x1800/188+2640+2814  eDP-1
 2: +HDMI-1 2160/597x3840/336+0+0  HDMI-1
```

When I am on `DP-1`, weird things happen. If I launch `xterm`, it does not appear on the current head. Note that my `Placement` settings are the following:

```
Placement {
	Model = "Centered"
}
```

Here is the information about that specific window that is nowhere to be found. The absolute `Y` position seems weird.

```
$ xwininfo -id 0x3a00012

xwininfo: Window id: 0x3a00012 "XTerm"

  Absolute upper-left X:  4790
  Absolute upper-left Y:  -10208
  Relative upper-left X:  6
  Relative upper-left Y:  50
  Width: 1200
  Height: 920
  Depth: 24
  Visual: 0x21
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x20 (installed)
  Bit Gravity State: NorthWestGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +4790+-10208  -10+-10208  -10-13902  +4790-13902
  -geometry 80x30-4+-10258
```

Now, if I go onto my `eDP-1` monitor, where things seem to be working smoothly, I create an `xterm` window there, and manually drag it to `DP-1`. Note that dragging windows across monitors works fine. Now that the `xterm` window is in the middle of `DP-1`, I double-click its titlebar to trigger the `fill` action, and it disappears again.

Another weird thing is that I have this configuration for edges:

```
MoveResize {
    EdgeAttract = "10"
    EdgeResist = "10"
}

Screen {
    ...

    EdgeSize = "40 40 40 40"
    EdgeIndent = "True"

    ...
}
```

And weirdly, if I create and select an `xterm` window from its titlebar, and try to move it around until I try to snap to the edges of `DP-1`, I end up being on my left `HDMI-1` monitor. See this screenshot where the `xterm` window is snapped at the edge:

<img width="6000" height="4614" alt="Image" src="https://github.com/user-attachments/assets/aa0413c9-5dc8-4708-9fb5-5744e0548038" />

So I believe there are some bugs with how PekWM calculates monitor positions on a multihead setup with a sophisticated arrangement. I don't know if this bug report has enough information, but let me know if you need more to diagnose what is happening.

Thanks a lot for your help in advance!

**Comment by pekdon** [comment]
So, this is basically two issues. One that is related to #190 where pekwm fails to properly handle updated XRandr information. The second one is the fact the pekwm currently only supports 1 edge and not one per head which _might_ be what one wants, depending on the layout and configured actions.

Moving a window between monitors, should not initiate a warp to another workspace as it does on actual edges, but depending on the layout it might be perceived as an actual edge.

**Comment by lobre** [comment]
I think I have an error now. Do you know how I can get you some logs?

Most of the time, as soon as I trigger my script to reload my monitors (containing `xrandr` instructions), I have PekWM, which crashes with `pekwm stopped unexpectedly`.

I have also had the case where it does not crash directly, but when I select the titlebar of a window, the window slides very fast in an unexpected position, and then it finally crashes.

I am running 5832c63a1615aa8492d731ad6d423d146b16e4e1, but I see that in the meantime, you have added new commits to `master`. So I will try to update to the latest version and report if it is still the same.

**Comment by pekdon** [comment]
Actually, I experienced the same today, a fix will come this afternoon.

**Comment by pekdon** [comment]
Hopefully should be working better now (however I will investigate this further when I have some more time on my hands)

**Comment by lobre** [comment]
I don't have the crash anymore. But I think the behavior is still not perfect.

I am still using the same layout as in my initial post, with my three monitors. The "red" border, for the edges, seems to be found on the left monitor, on the left side, and at the top (also on the left monitor, as it is the one that goes at the top).

However, I cannot stick to the right and bottom edges, respecting the gaps. Like my windows are snapped to the monitor border instead of at this edge gap.

Finally, when I create a window from any monitor, it always ends up being positioned on my `DP-1` monitor, instead of the current monitor.
